version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pipeline_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: form_etl_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: pipeline_redis
    ports:
      - "6379:6379"